version: '3.1'

services:
  db:
    image: postgres
    container_name: secutiry-jwt-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: secutiry-jwt-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: