# datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secutiry-jwt-db
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql